<?xml version="1.0" encoding="utf-8"?><Database Name="saledb" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-982V19O;Initial Catalog=saledb;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="saledbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.category" Member="categories">
    <Type Name="category">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="category_product" Member="products" ThisKey="id" OtherKey="category_id" Type="product" />
    </Type>
  </Table>
  <Table Name="dbo.order_detail" Member="order_details">
    <Type Name="order_detail">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="order_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="product_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="unit_price" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="num" Type="System.String" DbType="NVarChar(45)" CanBeNull="true" />
      <Association Name="product_order_detail" Member="product" ThisKey="product_id" OtherKey="id" Type="product" IsForeignKey="true" />
      <Association Name="sale_order_order_detail" Member="sale_order" ThisKey="order_id" OtherKey="id" Type="sale_order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.product" Member="products">
    <Type Name="product">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="price" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="manufacturer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="created_date" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="category_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="product_order_detail" Member="order_details" ThisKey="id" OtherKey="product_id" Type="order_detail" />
      <Association Name="category_product" Member="category" ThisKey="category_id" OtherKey="id" Type="category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.sale_order" Member="sale_orders">
    <Type Name="sale_order">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="amount" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="created_date" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="sale_order_order_detail" Member="order_details" ThisKey="id" OtherKey="order_id" Type="order_detail" />
      <Association Name="user_sale_order" Member="user" ThisKey="user_id" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[user]" Member="users">
    <Type Name="user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="NVarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="last_name" Type="System.String" DbType="NVarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="user_role" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="user_sale_order" Member="sale_orders" ThisKey="id" OtherKey="user_id" Type="sale_order" />
    </Type>
  </Table>
</Database>